# EE 16A Python Bootcamp SOLUTION
### EECS 16A: Designing Information Devices and Systems I, Fall 2020

# Table of Contents
* [Overview](#overview)
* [Python](#python)
    * [Control Flow](#ctrl)
    * [List Comprehension](#lst)
* [NumPy](#numpy)
    * [Arrays](#arrays)
    * [Slicing](#slice)
    * [Useful Functions](#funcs)
* [Miscellaneous Functions](#misc)
* [Questions](#qs)

<a id='overview'></a>
# Overview

This mini-lab serves as an introduction to IPython and a couple important packages we will be using throughout the semester. The lab aims to teach you proper usage of certain commands and can serve as a reference doc in the future. Even if you are a python wizard already, we recommend that you at least look through the lab to get re-acquainted with the functions we will be using a lot.

This lab is separated into two main parts: Guide and Questions. The Guide portion walks you through frequently used Python and IPython code, functions, and techniques. The Guide is supplemented with numerous blocks of example code to showcase concepts. The Questions portion of the lab is a collection of 10 problems meant to test your understanding of this guide. If you can answer these questions, then you have the knowledge to complete any and all programming tasks in EE 16A.

In [1]:
from __future__ import division
import numpy as np
import struct
import time
import warnings

warnings.filterwarnings("ignore")
import math
from numpy.linalg import inv
import struct
import random
import time
import scipy
from scipy import linalg
import random
import math
from IPython import display
from IPython.html.widgets import interact, interactive, fixed, interact_manual
import IPython.html.widgets as widgets
from IPython.display import display

print("Congratulations! Your Install is great!")

Congratulations! Your Install is great!


<a id='python'></a>
# Python

Both the labs and the homeworks in this course will require you to write some **Python** code. If you're new to programming, have no fear, as the assignments don't require more than just the fundamentals; **this is not round 2 of 61A.**

<a id='ctrl'></a>
## Control Flow in Python

Programming languages usually contain statements that can be used to direct or "control the flow" of execution. This includes (but is not limited to) conditional statements such as `if`, `else`, and `elif`, and loop-control statements such as `while`, `for`, `break`, and `continue`. 

### Conditional Statements: (if, else, elif)

In [2]:
# Example 1: Simple if/else

x = 16

if x > 20:  # Asking the question, "Is x greater than 20?"
    print("if condition is True!")
else:
    print("if condition is False!")

if condition is False!


In [3]:
# Example 2: Introducing elif

x = 16

if x > 20:  # Asking the question, "Is x greater than 20?"
    print("first if condition is True!")
elif x > 10 and x < 20:  # Asking the question, "Is x greater than 10 AND less than 20?"
    print("first if condition is False and second if condition is True!")
else:
    print("Neither if condition was True!")

first if condition is False and second if condition is True!


### Loop-Control Statements: (while, for)

In [4]:
# Example 3: while

i = 0
while (
    i < 5
):  # Check if i < 5 every iteration. Stop looping if the condition is false, i.e. if i >= 5.
    print("i:", i)
    i += 1  # increment i by 1

i: 0
i: 1
i: 2
i: 3
i: 4


Unlike while loops, which can theoretically run "forever" given the right condition, for loops serve a different purpose -- iterating a fixed number of times. For loops in Python expect an iterable object -- something similar to a list -- to control the number of iterations. The example below is "equivalent" to the while loop in the previous example.

In [5]:
# Example 4: for (pun intended)

for i in range(
    0, 5
):  # read about range() here: http://pythoncentral.io/pythons-range-function-explained/ .
    print("i:", i)

# Notice no i += 1 statement!

i: 0
i: 1
i: 2
i: 3
i: 4


In [6]:
# Example 5: Iterating through lists

char_list = [1, 6, "a"]
word = ""

for element in char_list:
    word += str(element)

print("word:", word)

word: 16a


All of the loop examples so far have terminated with some sort of stopping condition (i < 5, i in range(0,5), element in char_list). But what if we wanted to exit a loop early? Or, what if we wanted to immediately go to the next loop iteration? These two changes can be applied using the **break** and **continue** statements, respectively.

In [7]:
# Example 6: The break statement

candies = [
    "Skittles",
    "Snickers",
    "3 Musketeers",
    "Twizzlers",
    "Kit-Kat",
    "Twix",
    "Almond Joy",
]

print("Loop without break statement.")
for candy in candies:
    print(candy)

print("\nLoop with break statement.")
for candy in candies:
    print(candy)
    if candy == "Kit-Kat":
        break

Loop without break statement.
Skittles
Snickers
3 Musketeers
Twizzlers
Kit-Kat
Twix
Almond Joy

Loop with break statement.
Skittles
Snickers
3 Musketeers
Twizzlers
Kit-Kat


In [8]:
# Example 7: The continue statement

candies = [
    "Skittles",
    "Snickers",
    "3 Musketeers",
    "Twizzlers",
    "Kit-Kat",
    "Twix",
    "Almond Joy",
]

print("Same Loop as above but with continue instead of break statement.")
for candy in candies:
    print(candy)
    if candy == "Kit-Kat":
        continue

print("\nLoop that skips over every-other candy.")
for i in range(len(candies)):
    if (
        i % 2 == 1
    ):  # if i is odd. The "%" symbol is the modulo operator: https://en.wikipedia.org/wiki/Modulo_operation
        continue
    print(candies[i])

Same Loop as above but with continue instead of break statement.
Skittles
Snickers
3 Musketeers
Twizzlers
Kit-Kat
Twix
Almond Joy

Loop that skips over every-other candy.
Skittles
3 Musketeers
Kit-Kat
Almond Joy


**Notice how the continue statement enabled us to skip every-other candy.**

<a id='lst'></a>
## List Comprehension

There are multiple ways of creating lists in Python. If you recall from the first discussion, a list is a mutable array of data. They can be created using square brackets [ ]. Elements in the list are separated by commas. Elements can be of any type (int, string, float, etc.).

Important Python List functions: 

- `'+'` joins lists and creates a *new* list. 

- `len(x)` to get the length of list `x`


Next, we will explore the idea of list comprehension, which is a compact way of creating a list from a for-loop in a single line. Please keep in mind that list comprehension is just a style suggestion; any list comprehension can be expanded to a fully fleshed out control-loop block. However, the advantage of list comprehensions is their compact yet expressive syntax.


**For the example below, our goal is to create a list of the squares of each even integer in the range from 0 to 10 (inclusive).**

In [9]:
# Example 8a: for-loop list construction

# Expected output: [0*0, 2*2, 4*4, 6*6, 8*8, 10*10], which equals: [0, 4, 16, 36, 64, 100]

lst = []
for i in range(11):  # iterate over numbers 0 through 10 (inclusive)
    if i % 2 == 0:  # see example 7 for explanation of "%" symbol.
        lst += [
            i**2
        ]  # '**' is Python syntax for rasing the power. Alternatively: lst.append(i**2)

print(lst)

[0, 4, 16, 36, 64, 100]


In [10]:
# Example 8b: List Comprehension

lst = [i**2 for i in range(11) if i % 2 == 0]  # one-liner magic
print(lst)

[0, 4, 16, 36, 64, 100]


The syntax for a list comprehension is as follows:<br>
**list = ** **<span style="color:green">[</span>**<span style="color:red">function(</span>**ITEM**<span style="color:red">)</span> **<span style="color:green">for</span>** **ITEM** **<span style="color:green">in</span>** <span style="color:orange">ITERABLE_OBJECT</span> **<span style="color:green">if</span>** <span style="color:blue">condition(</span>**ITEM**<span style="color:blue">)</span>**<span style="color:green">]</span>**

In example 8b above:<br>
**ITEM** = i<br>
<span style="color:orange">ITERABLE_OBJECT</span> = range(11)<br>
<span style="color:red">function()</span> = raise **ITEM** to the second power<br>
<span style="color:blue">condition()</span> = is **ITEM** even?<br>

A couple notes: list comprehensions DO NOT require a condition, list comprehensions can have nested for-loops.

<a id='numpy'></a>
# NumPy

From the NumPy website, "NumPy is the fundamental package for scientific computing with Python. It contains among other things: a powerful N-dimensional array object." For the purposes of this course, we primarily use NumPy for its fast and fancy matrix functions. In general, Python list operations are slow; NumPy functions exploit the NumPy array object to "vectorize" the code, which usually improves the runtime of matrix calculations. **As a general rule of thumb, if a task involves vectors or matrices, you should resort to NumPy.** In addition to speeding up basic operations, NumPy contains an enormous library of matrix functions, so if you ever need to manipulate a vector or matrix, NumPy most likely already has a function implemented to suit your needs.

**Quintessential NumPy Documentation: http://docs.scipy.org/doc/numpy/reference/index.html**

**<span style="color:red">Run the cell below to import the packages needed to complete this lab.</span>**

In [11]:
import numpy as np  # from now on, we can access numpy functions by referencing "np" instead of numpy

<a id='arrays'></a>
## Creating a NumPy array object

NumPy is centered around the `numpy.array()` class. This array object is extremely useful, however, it is often confused with built-in Python lists, particularly when trying to represent vectors. NumPy arrays and Python Lists are NOT synonymous; you **cannot** simply apply functions to NumPy arrays as if they were Python Lists.

In [12]:
# Example 9: Going from Python list to NumPy array

py_lst = [1, 2, 3, 4]
np_arr = np.array(py_lst)
print("Python list:", py_lst)
print("NumPy array:", np_arr)

Python list: [1, 2, 3, 4]
NumPy array: [1 2 3 4]


In [13]:
# Example 10: Populating an empty NumPy array

np_arr = np.empty([4, 4], dtype=np.int)  # An empty 4x4 numpy array

for i in range(4):
    for j in range(4):
        np_arr[i, j] = i + j

print(np_arr)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [14]:
# Example 11: Creating a NumPy array of zeros and the Identity matrix

np_zeros = np.zeros([5, 5])  # 5x5 NumPy array of all zeros
np_id = np.eye(5)  # 5x5 Identity array

print("np_zeros:\n", np_zeros)
print("\nnp_id:\n", np_id)

np_zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np_id:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
# Example 12: Creating a NumPy array that spans a certain set/list of numbers

"""numpy.linspace() is useful when you know the number of divisions over a certain range you want, 
i.e., you want to divide the range [0-9] into 10 equal divisions.
"""
np_arr1 = np.linspace(0, 9, 10)  # args for linspace(): (start, stop, num_divisions)
print("np_arr1:", np_arr1)


"""numpy.arange() is useful when you know how far away each division is from one another, a.k.a. the step size.
You want to start at 0 and get every number that is 1 away from the previous number until you get to 9.
"""
np_arr2 = np.arange(0, 10, 1)  # args for arange(): (start, stop, step)
print("np_arr2:", np_arr2)

np_arr1: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
np_arr2: [0 1 2 3 4 5 6 7 8 9]


### NumPy array vs. Python List

Most arithmetic operations apply to NumPy arrays in element-wise fashion. This is in contrast with arithmetic operations for Python lists, which apply via concatenation.

In [16]:
# Example 13: NumPy array vs. Python list

lst = [1, 2, 3]
arr = np.eye(3)

lst2 = lst + lst
arr2 = arr + arr

print("lst:", lst)
print("lst + lst =", lst2)
print("\narr:\n", arr)
print("arr + arr =\n", arr2)

lst: [1, 2, 3]
lst + lst = [1, 2, 3, 1, 2, 3]

arr:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arr + arr =
 [[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


<a id='slice'></a>
## NumPy array slicing

Array slicing is a technique in Python (and other languages) that programmers use to extract specific index-based information from an array. Array slicing answers queries such as, "What are the first/last n elements in this array?", "What are the elements in the first r rows and first c columns of this matrix?", "What is every nth element in this array?"

In [17]:
# Example 14: Basic vector/list slicing

simple_arr = np.arange(0, 100, 1)

print("\nFirst ten elements of simple_arr:", simple_arr[:10])
print(
    "\nLast ten elements of simple_arr:", simple_arr[-10:]
)  # you should be aware that in Python,
# requesting a negative index (-n) from list a is the same as requesting is equivalent to requesting a[len(a)-n].
print(
    "\nElements 16-26 of simple_arr:", simple_arr[16:26]
)  # Notice slicing includes the first index and excludes that last index.


First ten elements of simple_arr: [0 1 2 3 4 5 6 7 8 9]

Last ten elements of simple_arr: [90 91 92 93 94 95 96 97 98 99]

Elements 16-26 of simple_arr: [16 17 18 19 20 21 22 23 24 25]


**<span style="color:red">Slicing includes the start index and excludes the end index, i.e. `simple_arr[16:26]` means to extract the values in `simple_arr` at indices in the range `[16,26)` which is the same as `[16,25]` since indices can only be integers.</span>**

In [18]:
# Example 15: Some fancy vector/list slicing

simple_arr = np.arange(0, 20, 1)

print("\nEvery-other element of simple_arr, starting from 0:", simple_arr[::2])
print("\nEvery-third element of simple_arr, starting from 0:", simple_arr[::3])
print("\nEvery-other element of simple_arr, starting from 10-16:", simple_arr[10:16:2])


Every-other element of simple_arr, starting from 0: [ 0  2  4  6  8 10 12 14 16 18]

Every-third element of simple_arr, starting from 0: [ 0  3  6  9 12 15 18]

Every-other element of simple_arr, starting from 10-16: [10 12 14]


In [19]:
# Example 16: Slicing NumPy arrays

i = np.array(range(25), dtype=np.int).reshape(
    [5, 5]
)  # numpy.reshape() will be introduced in the next cell
print("i:\n", i)

print("\nFirst row of i:", i[0])
print("\nFirst column of i:", i[:, 0])
print("\nRows 1-3 of i:\n", i[1:4])
print("\nColumns 1-3 of i:\n", i[:, 1:4])
print("\nTop left 3x3 of i:\n", i[:3, :3])
print("\nEvery-other column of i:\n", i[:, ::2])

i:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

First row of i: [0 1 2 3 4]

First column of i: [ 0  5 10 15 20]

Rows 1-3 of i:
 [[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Columns 1-3 of i:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]]

Top left 3x3 of i:
 [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]

Every-other column of i:
 [[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


### NumPy array reshaping

Reshaping is useful when you want to do something such as turn a vector into a matrix or vice-versa. We want to be able to do this because it is often easier to construct the desired array as a vector then reshape the vector into a matrix.

In [20]:
# Example 17: Determining the shape of a NumPy array

test_arr = np.zeros([15, 189])

print(
    "Shape of test_arr:", test_arr.shape
)  # Notice .shape is a NumPy array property NOT a function, i.e. no parenthesis.
print("Number of elements in test_arr:", test_arr.size)

Shape of test_arr: (15, 189)
Number of elements in test_arr: 2835


In [21]:
# Example 18: Using reshape()

test_arr = np.array(range(16), dtype=np.int)
print("\ntest_arr:", test_arr)
print("Shape of test_arr:", test_arr.shape)

test_arr_4x4 = test_arr.reshape(
    [4, 4]
)  # Notice reshape() is called on the array object, i.e. array.reshape(dimensions) NOT np.reshape(arr, dimensions)!
print("\nReshaped test_arr:\n", test_arr_4x4)
print("Shape of test_arr_4x4:", test_arr_4x4.shape)

test_arr_vec = test_arr_4x4.reshape(
    test_arr_4x4.size
)  # Use array.flatten() instead. This is just to show array.reshape works in both directions.
print("\ntest_arr back as a vector:", test_arr_vec)
print("Shape of test_arr_vec:", test_arr_vec.shape)


test_arr: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Shape of test_arr: (16,)

Reshaped test_arr:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Shape of test_arr_4x4: (4, 4)

test_arr back as a vector: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Shape of test_arr_vec: (16,)


<a id='funcs'></a>
## Useful NumPy functions: (transpose(), linalg.inv(), dot(), concatenate(), vstack(), hstack(), max(), argmax())

**Quintessential NumPy Documentation: http://docs.scipy.org/doc/numpy/reference/index.html**

In [22]:
# Example 19: numpy.transpose()

norm = np.array(range(16), dtype=np.int).reshape([4, 4])
print("\nnorm:\n", norm)

norm_transpose = np.transpose(norm)
print("\nnorm_transpose:\n", norm_transpose)

print("\nnorm easy transpose:\n", norm.T)  # numpy.transpose(arr) == arr.T


norm:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

norm_transpose:
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]

norm easy transpose:
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [23]:
# Example 20: numpy.linalg.inv (finds the inverse of a matrix)

i = np.eye(4)
print("\ni:\n", i)

i_inv = np.linalg.inv(i)  # Notice .inv() is a function in the linalg library of NumPy.
print("\ni_inv:\n", i_inv)
print("\nAs expected, i == inv(i).")


i:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

i_inv:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

As expected, i == inv(i).


In [24]:
# Example 21a: numpy.dot() (how to do matrix multiplication in NumPy!)

a = np.array([[2, 3], [4, 5]])
print("\na:\n", a)
b = np.array([[1, 2], [0, 2]])
print("\nb:\n", b)

print("\nMatrix multiplication.")
c = np.dot(a, b)
print("a*b:\n", c)

print("\nOrder matters in numpy.dot()!")
d = np.dot(b, a)
print("b*a:\n", d)
print("Notice a*b != b*a.")

e = np.array([2, 2])
print("\ne:", e)

print("\nnumpy.dot() can be used to multiply an array and vector too.")
f = np.dot(a, e)
print("a*e:", f)


a:
 [[2 3]
 [4 5]]

b:
 [[1 2]
 [0 2]]

Matrix multiplication.
a*b:
 [[ 2 10]
 [ 4 18]]

Order matters in numpy.dot()!
b*a:
 [[10 13]
 [ 8 10]]
Notice a*b != b*a.

e: [2 2]

numpy.dot() can be used to multiply an array and vector too.
a*e: [10 18]


**Instead of using `numpy.dot()` to perform matrix multiplication, NumPy provides an alternative using the `*` operator.** Up until now, we've been exclusively dealing with NumPy `arrays`; but there is another NumPy class called `matrix`. A NumPy `matrix` is just a 2-dimensional NumPy `array`, except it has a few additional features. In particular, we can use the `*` operator to perform multiplication of two NumPy `matrices` (we CANNOT use `*` when multiplying NumPy `arrays`).

In [25]:
# Example 21b: NumPy matrix multiplication
a = np.matrix([[2, 3], [4, 5]])
print("\na:\n", a)
b = np.matrix([[1, 2], [0, 2]])
print("\nb:\n", b)

print("\nMatrix multiplication using * operator.")
c = a * b
print("a*b:\n", c)


a:
 [[2 3]
 [4 5]]

b:
 [[1 2]
 [0 2]]

Matrix multiplication using * operator.
a*b:
 [[ 2 10]
 [ 4 18]]


In [26]:
# Example 22: numpy.concatenate() (how to append/attach multiple arrays.)

a = np.array([[2, 3], [4, 5]])
print("\na:\n", a)
b = np.array([[1, 2], [0, 2]])
print("\nb:\n", b)

c = np.concatenate(
    [a, b], axis=0
)  # axis controls how to concatenate the arrays. axis=0 attach vertically, axis=1 attach horizontally.
print('\nAppend b to the "bottom" of a:\n', c)

d = np.concatenate([a, b], axis=1)
print('\nAppend b to the "right" of a:\n', d)


a:
 [[2 3]
 [4 5]]

b:
 [[1 2]
 [0 2]]

Append b to the "bottom" of a:
 [[2 3]
 [4 5]
 [1 2]
 [0 2]]

Append b to the "right" of a:
 [[2 3 1 2]
 [4 5 0 2]]


In [27]:
# Example 23: numpy.vstack() and numpy.hstack()

a = np.array([[2, 3], [4, 5]])
print("\na:\n", a)
b = np.array([[1, 2], [0, 2]])
print("\nb:\n", b)

c = np.vstack([a, b])
print("\nvstack a and b:\n", c)
print("Notice this is equivalent to concatenate with axis=0.")

d = np.hstack([a, b])
print("\nhstack a and b:\n", d)
print("Notice this is equivalent to concatenate with axis=1.")


a:
 [[2 3]
 [4 5]]

b:
 [[1 2]
 [0 2]]

vstack a and b:
 [[2 3]
 [4 5]
 [1 2]
 [0 2]]
Notice this is equivalent to concatenate with axis=0.

hstack a and b:
 [[2 3 1 2]
 [4 5 0 2]]
Notice this is equivalent to concatenate with axis=1.


<a id='misc'></a>
# Miscellaneous Functions

In [28]:
# Example 24: np.floor(), np.ceil()

a = 16.5
print("a:", a)
print("floor of a:", np.floor(a))
print("ceiling of a:", np.ceil(a))

a: 16.5
floor of a: 16.0
ceiling of a: 17.0


In [29]:
# Example 25: np.max(), np.min(), np.argmax(), np.argmin()

a = np.array([0, 1, 2, 3, 16, 3, 2, 1, 0])
print("a:", a)
print("max of a =", np.max(a))
print("min of a =", np.min(a))
print("index of max value of a =", np.argmax(a))
print("index of min value of a =", np.argmin(a))

a: [ 0  1  2  3 16  3  2  1  0]
max of a = 16
min of a = 0
index of max value of a = 4
index of min value of a = 0


<a id='qs'></a>
# Questions and Solutions

These questions are in no particular order (except for question 0, do that one first). The questions range in difficulty; some are one-liners, others require a lot more thinking. Don't be discouraged if you hit a roadblock. Talk to your neighbors and ask for help from the lab staff.

## <span style="color:blue"> Note: There are multiple possible solutions to each question. Shown below are just a few of these solutions. </span>
### Question 0
**<span style="color:red">In order to test your code, plase run the cell below to load the autograder. There is a cell after each question that you can run in order to check your answer. The autograder is purposefully not very verbose.</span>**

In [30]:
%run autograder.py

Autograder loaded!
Question 0 Passed!


### Question 1
**<span style="color:red">Search the NumPy documentation and/or the web for a NumPy function that can solve a system of linear equations of the form `Ax=b`. Once you've found the package and function, insert those names into the `package` and `function` placeholders in the cell below. Often Googling `Numpy` followed by the function you'd like will giv eyou exactly what you want. Ex: Try searching `Numpy Matrix Solver`</span>**

In [31]:
# find the missing package and function

func = np.linalg.solve  # YOUR CODE HERE


# Do not modify the code below
def q1(A, b):
    return func(A, b)

In [32]:
test_q1(q1)

Question 1 Passed!


### Question 2
**<span style="color:red">Given NumPy array A, return an array that consists of every entry of A that is in an even row and in an odd column. </span>**

See [slicing](#slice) for examples on how to do array slicing.

In [33]:
def q2(A):
    """
    Input:
    A - MxN NumPy array

    Output:
    Returns an NumPy array that consists of every entry of A that has an even row index and has an odd column index.

    Example:
    A = np.array([[ 1  2  3  4  5]
                  [ 6  7  8  9 10]
                  [11 12 13 14 15]
                  [16 17 18 19 20]
                  [21 22 23 24 25]])

    Output = np.array([[ 2  4]
                       [12 14]
                       [22 24]])
    """

    # YOUR CODE HERE
    """
    Recall the syntax for array slicing: 
    
        A[starting_row: ending_row: #rows_to_skip, starting_column: ending_column: #columns_to_skip]
        
    * Default start row/column = 0
    * Default end row/column = last 
    
    Starting with row 0 and skipping 2 rows each time gives us rows 0, 2, 4 ... 
    Starting with column 1 and skipping 2 rows each time gives us columns 1, 3, 5 ...
    """
    return A[::2, 1::2]

In [34]:
test_q2(q2)

Question 2 Passed!


### Question 3
**<span style="color:red">Given an MxN NumPy array, first find the indices of the maximum value in each row of the array, then return the maximum index.</span>**

Hint: There is a function to find the index of the maximum value on a vector.

Hint 2: List Comprehensions and Iterators might be useful.

In [35]:
def q3(A):
    """
    Input:
    A - MxN NumPy array

    Output:
    Return the maximum index of maximum row values of A.

    Example:
    A = np.array([[0 1 0 0]
                  [1 0 0 0]
                  [0 0 0 0]
                  [0 0 1 0]])

    Output = 2
    """

    # YOUR CODE HERE
    """
    Step 1: Find indices of the maximum value in each row of the array - use np.argmax() 
        We can create a new Python list that stores the maximum indices for each row 
        
    Step 2: Find the maximum in this newly created list - use max()
    
    Note: getting the dimensions of A
    * np.shape(A) returns a tuple of the form (#rows, #columns)
    * A.shape also returns a tuple of the form (#rows, #columns)
    * len(A) returns the number of rows in A
    * len(A[0]) returns the number of columns in A
    
    """

    # Solution 1:
    """
    max_indices = []

    for i in range(np.shape(A)[0]):
        ith_row = A[i]
        max_indices.append(np.argmax(ith_row))
    return max(max_indices)
    """

    # Solution 2: a more compact version
    max_indices = [np.argmax(A[i]) for i in range(np.shape(A)[0])]
    return max(max_indices)

In [36]:
test_q3(q3)

Question 3 Passed!


### Question 4
**<span style="color:red">Given two MxN NumPy arrays, copy every-other column of array A to the right side of array B. </span>**

See [slicing](#slice) for examples on how to do array slicing.

In [37]:
def q4(A, B):
    """
    Inputs:
    A - MxN NumPy array
    B - MxP NumPy array

    Output:
    Returns an Mx(P+(N/2)) NumPy array where every-other column of A is added to the right side of B in order,
    starting from index 0.

    Example:
    A = np.array([[1,0,0,2]
                  [0,1,0,2]
                  [0,0,1,2]])
    B = np.array([[1,2,3]
                  [4,5,6]
                  [7,8,9]])

    Output = np.array([[1,2,3,1,0]
                       [4,5,6,0,0]
                       [7,8,9,0,1]])
    """

    # YOUR CODE HERE

    """
    Step 1: create a temporary matrix storing every-other column of A - using array slicing
    
    Step 2: append the temporary matrix to the right side of B - use np.concatenate(), or np.hstack()
    """

    # Solution 1:
    """
    #Note: A[:, 0::2] is equivalent to A[0::1, 0::2]

    every_other_col_A = A[:, 0::2]
    return np.hstack((B, every_other_col_A))
    """

    # Solution 2: a more compact version

    return np.hstack((B, A[:, 0::2]))

    # Solution 3: using np.concatenate()
    """
    return np.concatenate((B, A[:,::2]), axis=1)
    """

In [38]:
test_q4(q4)

Question 4 Passed!


### Question 5
**<span style="color:red">Given vectors u = [1,2,3,...,N] and v = [2017,2018,2019,...,2017+N-1], create a vector that contains the following sequence: [1`*`2017, 2`*`2018, 3`*`2019,...,N`*`(2017+N-1)].</span>**

In [39]:
def q5(N):
    """
    Input:
    N - number of elements in u and v.

    Output:
    Returns the sequence: np.array([1*2017,2*2018,...,N*(2017+N-1)])

    Example:
    N = 5

    Output = np.array([ 2017  4036  6057  8080 10105])
    """

    # YOUR CODE HERE

    """
    Step 1: create u vector - use np.arange()
    
    Step 2: create v vector - use np.arange()
    
    Step 3: multiply u by v elementwise
    """
    # Solution:

    # Note: the stopping value is NOT included in the list - since we want the last value in the list to be N,
    # we need to set the stopping index to N+1

    # args for arange(): (start, stop, step_size) - step_size is optional and defaults to 1
    u = np.arange(1, N + 1, 1)
    v = np.arange(2017, 2017 + N)

    return u * v

In [40]:
test_q5(q5)

Question 5 Passed!


### Question 6
**<span style="color:red">Given a NumPy vector v, shift all of the elements in v by n steps to the right; values that "fall off" the right end of v get inserted at the beginning of v, thus the length of v is preserved. You can either attempt to implement this on your own, or, (hint hint) try searching for a related NumPy function that does some/all of the work for you... </span>**

In [41]:
def q6(v, N=10):
    """
    Input:
    v = NumPy vector
    N = number of steps to shift v to the right

    Output:
    Returns v shifted to the right by N steps.

    Example:
    v = np.array([0,1,2,3,4,5])
    N = 3

    Output = np.array([3,4,5,0,1,2])
    """

    # YOUR CODE HERE

    # Use the np.roll() function
    # args for np.roll(): (array, number_of_steps_to_shift)

    return np.roll(v, N)

In [42]:
test_q6(q6)

Question 6 Passed!


### Question 7
**<span style="color:red">Given an MxM identity matrix, convert this to an (M-N)x(M-N) identity matrix WITHOUT using numpy.eye().</span>**

In [43]:
def q7(I=np.eye(10), N=4):
    """
    Input:
    I - MxM NumPy array representing the identity matrix
    N - number os rows and columns to cut from I

    Output:
    Returns an (M-N)x(M-N) NumPy identity array.

    Example:
    I = np.eye(10)
    N = 8

    Output = np.array([[1,0]
                       [0,1]])
    """

    # YOUR CODE HERE; REMEMBER, YOU CANNOT USE np.eye()! Array Slicing is very helpful!

    """
    We want to select the first M-N rows and first M-N columns of the input I matrix
    Step 1: find the value of M
    
    Step 2: use array slicing to select the necessary rows and columns
    """
    # Solution 1:
    """
    M = I.shape[0]
    new_I = I[0:M-N, 0:M-N]
    
    return new_I
    """

    # Solution 2: a more compact version
    # Note: here I.shape[0] = I.shape[1] since the I matrix is square

    return I[: I.shape[0] - N, : I.shape[1] - N]

In [44]:
test_q7(q7)

Question 7 Passed!


### Question 8
**<span style="color:red">Given a square NxN NumPy array A, return a Python list of the values along the diagonal of A, sorted in descending order.</span>**

Hint: Python has a `sort` function that can operate on lists, but not Numpy arrays

In [45]:
def q8(A):
    """
    Input:
    A - NxN NumPy array

    Output:
    Returns a Python list containing the diagonal of A sorted in descending order.

    Example:
    A = np.array([[1,2,3]
                   [4,5,6]
                   [7,8,9]])

    Output = [9,5,1]
    """

    # YOUR CODE HERE

    """
    Step 1: create a list that stores the diagonal elements of A
    
    Step 2: sort this list in descending order - use sorted()
    
    * Alternatively, you can also use np.diag()
    """

    # Solution 1:
    """
    diag_elems = []
    for i in range(A.shape[0]):
        ith_diag_elem = A[i, i]
        diag_elems.append(ith_diag_elem)
    return sorted(diag_elems, reverse=True)
    """

    # Solution 2: a more compact version
    """
    diag_elems = [A[i, i] for i in range(A.shape[0])]
    return sorted(diag_elems, reverse = True)
    """

    # Solution 3: alternate solution using np.diag():
    # https://numpy.org/doc/stable/reference/generated/numpy.diag.html

    diag_elems = np.diag(A)  # (Unsorted) Diagonal elements of A
    return sorted(diag_elems, reverse=True)

In [46]:
test_q8(q8)

Question 8 Passed!


### Question 9
**<span style="color:red">Given two differently sized matrices, "pad" the matrices with the smaller dimensions with rows/columns of zeros until they are the same size as one another. Add the padding to the bottom (if adding rows) and to the right (if adding columns). Hint: there might be a NumPy function that does something similar/exactly to this, but it's good practice to try this yourself.  </span>**

This is typically the hardest questions for students.

In [47]:
def q9(A, B):
    """
    Input:
    A - MxN NumPy array
    B - YxZ NumPy array

    Output:
    Returns the zero-padded versions of each array such that they are of equivalent dimensions.
    Padding is added to the bottom and right.

    Example:
    A = np.array([[1,2,3]
                   [4,5,6]])
    B = np.array([[1,1]
                  [1,1]
                  [1,1]])

    Output = np.array([[1,2,3]
                        [4,5,6]
                        [0,0,0]]),
              np.array([[1,1,0]
                        [1,1,0]
                        [1,1,0]])
    """

    # YOUR CODE HERE

    """
    Step 1: identify the correct dimension for the padded matrices (let's call them A_pad and B_pad)
        Step 1a: identify whether M or Y is larger - this will be number of rows in the padded matrices
        Step 1b: identify whether N or Z is larger - this will be number of columns in the padded matrices
    
    Step 2: Create the matrices A_pad and B_pad, but fill them with all 0's to begin with
    
    Step 3: Fill in A_pad with the rows from A - assigning to an array slice is used here
    
    Step 4: Fill in B_pad with the rows from B - assigning to an array slice is used here
    
    Step 5: Set A, B to the newly padded matrices A_pad and B_pad
    
    """
    # Solution

    # Step 1
    (M, N) = A.shape
    (Y, Z) = B.shape

    padded_num_rows = max(M, Y)
    padded_num_cols = max(N, Z)

    # Step 2
    A_pad = np.zeros((padded_num_rows, padded_num_cols))
    B_pad = np.zeros((padded_num_rows, padded_num_cols))

    # Step 3
    A_pad[:M, :N] = A

    # Step 4
    B_pad[:Y, :Z] = B

    # Step 5
    # A = A_pad
    # B = B_pad

    return A_pad, B_pad

In [48]:
test_q9(q9)

Question 9 Passed!


### Question 10
**<span style="color:red">Given an MxN matrix, A, and an NxM matrix, B, concatenate (side-by-side) the first p rows of A with the transpose of the last p columns of B.</span>**

In [49]:
def q10(A, B, p):
    """
    Input:
    A - MxN NumPy array
    B - NxM NumPy array
    p - number of rows from A to concatenate with number of columns from B

    Output:
    Returns the side-by-side concatenation of the first p rows of A with the transpose of the last p columns of B.

    Example:
    A = np.array([[1,1,1]
                  [1,1,1]
                  [1,1,1]
                  [1,1,1]])
    B = np.array([[1,2,3,4]
                  [5,6,7,8]
                  [9,10,11,12]])
    p = 2

    Output = np.array([[1,1,1,3,7,11]
                       [1,1,1,4,8,12]])
    """

    # YOUR CODE HERE

    """
    Step 1: create a matrix with the first p rows of A (called A_new)
    
    Step 2: calculate which column to start at in order to select the last p columns of B
    
    Step 3: create a matrix with the last p columns of B (called B_new)
    
    Step 4: concatenate A_new and the transpose of B_new - use np.hstack() or np.concatenate()
    """

    # Solution 1
    """
    A_new = A[:p]
    
    # To know which column of B we want to start with, we can do the following:
    B_num_cols = B.shape[1]
    B_start_col = B_num_cols - p
    
    B_new = B[:, B_start_col:] 
    #This is equivalent to B[:, -p:] which will automatically start at the (B_num_cols - p)th column (inclusive of this column)
    
    return np.hstack((A_new, B_new.T)) 
    """

    # Solution 2: a more compact version
    return np.hstack(
        (A[:p], B[:, -p:].T)
    )  # equivalent to: np.concatenate((A[:p], B[:,-p:].T), axis=1)

In [50]:
test_q10(q10)

Question 10 Passed!


In [51]:
test_all(q1, q2, q3, q4, q5, q6, q7, q8, q9, q10)

Question 1 Passed!
Question 2 Passed!
Question 3 Passed!
Question 4 Passed!
Question 5 Passed!
Question 6 Passed!
Question 7 Passed!
Question 8 Passed!
Question 9 Passed!
Question 10 Passed!
